In [1]:
import cv2
import numpy as np
# Load the two images
img1 = cv2.imread('pancard.png', 0)
img2 = cv2.imread('research intern.png', 0)

# Define corresponding points)
pts1 = np.array([
    [100, 200],
    [150, 180],
    [200, 160],
    [250, 140],
    [300, 120],
    [350, 100],
    [400, 80],
    [450, 60]
], dtype=np.float32)

pts2 = np.array([
    [300, 50],
    [350, 70],
    [400, 90],
    [450, 110],
    [500, 130],
    [550, 150],
    [600, 170],
    [650, 190]
], dtype=np.float32)



In [2]:
# Normalize the points
pts1_normalized = cv2.normalize(pts1, None, 0, 1, cv2.NORM_MINMAX)
pts2_normalized = cv2.normalize(pts2, None, 0, 1, cv2.NORM_MINMAX)
# Estimate the essential matrix using the normalized points
F, _ = cv2.findEssentialMat(pts1_normalized, pts2_normalized)
# Print the estimated essential matrix
print("Estimated Essential Matrix:")
print(F)


Estimated Essential Matrix:
[[-0.17503769 -0.2446146   0.09334363]
 [ 0.23845178  0.11368067  0.65577755]
 [-0.34219605 -0.48740209  0.21523661]]


In [6]:
# Estimate the fundamental matrix using the normalized 

F, _ = cv2.findFundamentalMat(pts1_normalized, pts2_normalized)
# Print the estimated fundamental matrix


print("Estimated Fundamental Matrix:")
print(F)



Estimated Fundamental Matrix:
None
