In [5]:
import numpy as np

a1 = np.array([[16,1,2,3],[4,5,6,7],[8,9,17,11],[12,13,14,15]])

In [6]:
a1

array([[16,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 17, 11],
       [12, 13, 14, 15]])

# Transposing the matrix

In [7]:
print(np.transpose(a1))  #using inbulit function

[[16  4  8 12]
 [ 1  5  9 13]
 [ 2  6 17 14]
 [ 3  7 11 15]]


In [8]:
result = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]  #transposing the matrix without inbulit function 
#using loops

# iterate through rows
for i in range(len(a1)):
   # iterate through columns
   for j in range(len(a1[0])):
       result[j][i] = a1[i][j]

for r in result:
   print(r)

[16, 4, 8, 12]
[1, 5, 9, 13]
[2, 6, 17, 14]
[3, 7, 11, 15]


In [11]:
def transpose(a1):
    for i in range(len(a1)):
        for j in range(i+1,len(a1)):
            a1[i][j],a1[j][i] = a1[j][i],a1[i][j]
    return a1

transpose(a1)
#print(len(a1))
            

array([[16,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 17, 14],
       [ 3,  7, 11, 15]])

# determinant of matrix

In [13]:
det = np.linalg.det(a1)
print(int(det))

-1792


# inverse of the matrix

In [14]:
print(np.linalg.inv(a1))

[[ 0.0625     -0.09375     0.          0.03125   ]
 [-0.09375    -0.76116071 -0.07142857  0.80133929]
 [ 0.         -0.07142857  0.14285714 -0.07142857]
 [ 0.03125     0.42633929 -0.07142857 -0.26116071]]
