In [1]:

import pandas as pd
import numpy as np

x = np.array([[1,2,3,4],[4,3,2,1]])
print(x)


[[1 2 3 4]
 [4 3 2 1]]


In [2]:
x.reshape(4,2)

array([[1, 2],
       [3, 4],
       [4, 3],
       [2, 1]])

In [3]:
np.resize(x,(2,4))

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [4]:

import pandas as pd
data = {'Name': ['Jai', 'Princ', 'Gaurav', 'Anuj'],'Height': [5.1, 4.2, 4.9, 6.2],'Qualification': ['Btech', 'Btech', 'Ms', 'Bsc']}
df = pd.DataFrame(data,index = ['a','b','c','d'])
address = ['Delhi', 'Bangalore', 'Punjab','Bihar']
df['Native place'] = address
print(df)


     Name  Height Qualification Native place
a     Jai     5.1         Btech        Delhi
b   Princ     4.2         Btech    Bangalore
c  Gaurav     4.9            Ms       Punjab
d    Anuj     6.2           Bsc        Bihar


In [5]:
data = [5,4,3,2,1]
x= pd.Series(data,index=['p','q','r','s','t'])
x

p    5
q    4
r    3
s    2
t    1
dtype: int64

In [6]:
df = {"col1": pd.Series([1,2,3,4],index = ['a','b','c','d']),"col2" : pd.Series([4,5,6],index = ['x','y','z'])}
ans = pd.DataFrame(df)
print(ans)

   col1  col2
a   1.0   NaN
b   2.0   NaN
c   3.0   NaN
d   4.0   NaN
x   NaN   4.0
y   NaN   5.0
z   NaN   6.0


In [7]:
ans.loc['b'] = [5,'NaN']
#ans.loc[b] = [5] it prints in that full row that value which was assigned.. 
ans

col1 col2
a   1.0  NaN
b   5.0  NaN
c   3.0  NaN
d   4.0  NaN
x   NaN  4.0
y   NaN  5.0
z   NaN  6.0

In [8]:
ans.loc['z'] = ['NaN',9]
ans

col1 col2
a  1.0  NaN
b  5.0  NaN
c  3.0  NaN
d  4.0  NaN
x  NaN  4.0
y  NaN  5.0
z  NaN    9

In [9]:
ans = pd.DataFrame(df,dtype='int')
print(ans.dtypes)

col1    float64
col2    float64
dtype: object
